"""init schema tables

Revision ID: 4591dee5c8d6
Revises: 
Create Date: 2020-11-18 16:29:10.619479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4591dee5c8d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=24), nullable=True),
    sa.Column('symbol_group', sa.VARCHAR(length=18), nullable=True),
    sa.Column('asset_class', sa.VARCHAR(length=3), nullable=True),
    sa.Column('expiry', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_asset_class'), 'symbols', ['asset_class'], unique=False)
    op.create_index(op.f('ix_symbols_expiry'), 'symbols', ['expiry'], unique=False)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=False)
    op.create_index(op.f('ix_symbols_symbol_group'), 'symbols', ['symbol_group'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('algo', sa.VARCHAR(length=32), nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=12), nullable=True),
    sa.Column('direction', sa.VARCHAR(length=5), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.VARCHAR(length=8), nullable=True),
    sa.Column('order_type', sa.VARCHAR(length=6), nullable=True),
    sa.Column('market_price', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('target', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('stop', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('entry_price', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('exit_price', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('realized_pnl', sa.FLOAT(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('algo', 'symbol', 'entry_time')
    )
    op.create_index(op.f('ix_trades_algo'), 'trades', ['algo'], unique=False)
    op.create_index(op.f('ix_trades_entry_price'), 'trades', ['entry_price'], unique=False)
    op.create_index(op.f('ix_trades_entry_time'), 'trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trades_exit_price'), 'trades', ['exit_price'], unique=False)
    op.create_index(op.f('ix_trades_exit_reason'), 'trades', ['exit_reason'], unique=False)
    op.create_index(op.f('ix_trades_exit_time'), 'trades', ['exit_time'], unique=False)
    op.create_index(op.f('ix_trades_market_price'), 'trades', ['market_price'], unique=False)
    op.create_index(op.f('ix_trades_order_type'), 'trades', ['order_type'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_table('bars',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol_id', sa.SMALLINT(), nullable=False),
    sa.Column('open', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('high', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('low', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('close', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datetime', 'symbol_id')
    )
    op.create_index(op.f('ix_bars_datetime'), 'bars', ['datetime'], unique=False)
    op.create_index(op.f('ix_bars_symbol_id'), 'bars', ['symbol_id'], unique=False)
    op.create_table('ticks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol_id', sa.SMALLINT(), nullable=False),
    sa.Column('bid', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('bidsize', sa.INTEGER(), nullable=True),
    sa.Column('ask', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('asksize', sa.INTEGER(), nullable=True),
    sa.Column('last', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('lastsize', sa.INTEGER(), nullable=True),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datetime', 'symbol_id')
    )
    op.create_index(op.f('ix_ticks_datetime'), 'ticks', ['datetime'], unique=False)
    op.create_index(op.f('ix_ticks_symbol_id'), 'ticks', ['symbol_id'], unique=False)
    op.create_table('greeks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tick_id', sa.INTEGER(), nullable=True),
    sa.Column('bar_id', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('underlying', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('dividend', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('iv', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('oi', sa.FLOAT(asdecimal=True), nullable=True),
    sa.Column('delta', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('gamma', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('theta', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('vega', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['tick_id'], ['ticks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_greeks_bar_id'), 'greeks', ['bar_id'], unique=False)
    op.create_index(op.f('ix_greeks_tick_id'), 'greeks', ['tick_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_greeks_tick_id'), table_name='greeks')
    op.drop_index(op.f('ix_greeks_bar_id'), table_name='greeks')
    op.drop_table('greeks')
    op.drop_index(op.f('ix_ticks_symbol_id'), table_name='ticks')
    op.drop_index(op.f('ix_ticks_datetime'), table_name='ticks')
    op.drop_table('ticks')
    op.drop_index(op.f('ix_bars_symbol_id'), table_name='bars')
    op.drop_index(op.f('ix_bars_datetime'), table_name='bars')
    op.drop_table('bars')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_type'), table_name='trades')
    op.drop_index(op.f('ix_trades_market_price'), table_name='trades')
    op.drop_index(op.f('ix_trades_exit_time'), table_name='trades')
    op.drop_index(op.f('ix_trades_exit_reason'), table_name='trades')
    op.drop_index(op.f('ix_trades_exit_price'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_time'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_price'), table_name='trades')
    op.drop_index(op.f('ix_trades_algo'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_symbols_symbol_group'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_expiry'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_asset_class'), table_name='symbols')
    op.drop_table('symbols')
    # ### end Alembic commands ###
